"""
research/scripts/regenerate_ground_truth.py
================================================================
Replaces pretrain_data/ec3_optimal_designs.csv (generated by the
ORIGINAL generate_ec3_pretrain_dataset.py, which (a) used the pre-audit,
pre-fix EC3 code -- specifically missing the EN1993-1-1 Table 6.5 curve-d
case for welded h/b>2 sections -- and (b) used a coarse 9^4-point grid
search per context, empirically shown by research/tests/
validate_ground_truth.py to miss meaningfully better designs on the
majority of a random sample) with a version that:

    1. Uses research.envs.hss_env.HSSBeamEnv directly (the fixed,
       independently-verified EC3 implementation), not a dynamically
       loaded copy of the original exp54b environment.
    2. Uses a multi-restart genetic algorithm (research/scripts/
       ga_baseline.py's ga_design_fixed_grade), validated in
       validate_ground_truth.py to reliably outperform the coarse grid,
       instead of grid search.

Same context grid as the original (12 spans x 12 loads x 6 grades x 2
section types = 1,728 contexts), so this is a drop-in replacement with
the identical CSV schema (span_m, load_kNm, grade, section_type, h, b,
tf, tw, util, mass, cost, co2, governing) -- every downstream script
(evaluate.py, grade_policy_analysis.py, generalization_test.py) needs no
changes.

RUNTIME: at pop_size=50, n_generations=80, n_restarts=2 (the defaults
below), each (context, restart) takes roughly 0.4-0.6s on a single CPU
core (measured during the pre-Experiment-1 audit), so the full 1,728-
context x 2-restart run is approximately 25-35 minutes single-threaded.
This is a genuine "regenerate the reference dataset" computation, not a
quick unit test -- run explicitly, not as a side effect of anything else.

USAGE
------
    python research/scripts/regenerate_ground_truth.py \\
        --out pretrain_data/ec3_optimal_designs_v2.csv \\
        --pop_size 50 --n_generations 80 --n_restarts 2

    # Small-scale validation run (for confirming the script itself works):
    python research/scripts/regenerate_ground_truth.py \\
        --out /tmp/ec3_optimal_designs_smoketest.csv \\
        --n_spans 3 --n_loads 3 --pop_size 30 --n_generations 40 --n_restarts 1
================================================================
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import numpy as np
import pandas as pd

from research.envs.hss_env import HSSBeamEnv
from research.scripts.ga_baseline import ga_design_fixed_grade

GRADES = [355, 460, 500, 550, 620, 690]
SECTION_TYPES = ["rolled", "welded"]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="pretrain_data/ec3_optimal_designs_v2.csv")
    p.add_argument("--span_min_m", type=float, default=6.0)
    p.add_argument("--span_max_m", type=float, default=15.0)
    p.add_argument("--load_min", type=float, default=20.0)
    p.add_argument("--load_max", type=float, default=140.0)
    p.add_argument("--n_spans", type=int, default=12)
    p.add_argument("--n_loads", type=int, default=12)
    p.add_argument("--pop_size", type=int, default=50)
    p.add_argument("--n_generations", type=int, default=80)
    p.add_argument("--n_restarts", type=int, default=2)
    p.add_argument("--economy_metric", default="mass",
                    help="What the GA minimises per (grade,type) cell -- 'mass' matches "
                         "the original dataset's semantics (min-mass feasible geometry "
                         "for that fixed grade/type); cost/co2 for that cell are still "
                         "reported in the output row regardless, computed at the mass-"
                         "optimal geometry, matching the original schema.")
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()

    spans = np.linspace(args.span_min_m, args.span_max_m, args.n_spans)
    loads = np.linspace(args.load_min, args.load_max, args.n_loads)
    contexts = [(s, l, g, t) for s in spans for l in loads for g in GRADES for t in SECTION_TYPES]
    print(f"Regenerating ground truth: {len(contexts)} contexts "
          f"({args.n_spans} spans x {args.n_loads} loads x {len(GRADES)} grades x 2 types), "
          f"pop={args.pop_size}, gens={args.n_generations}, restarts={args.n_restarts}")
    print(f"Estimated runtime: ~{len(contexts) * args.n_restarts * 0.5 / 60:.1f} minutes\n")

    rows = []
    t0 = time.time()
    for i, (span_m, load_kNm, grade, section_type) in enumerate(contexts):
        best_result, best_mass = None, np.inf
        for restart in range(args.n_restarts):
            result = ga_design_fixed_grade(
                span_mm=span_m * 1000.0, load_kNm=load_kNm, storey=20,
                grade=grade, section_type=section_type, economy_metric=args.economy_metric,
                pop_size=args.pop_size, n_generations=args.n_generations,
                seed=args.seed * 100000 + i * 10 + restart,
            )
            if result["feasible"] and result["mass"] < best_mass:
                best_mass, best_result = result["mass"], result

        if best_result is None:
            print(f"  [{i+1}/{len(contexts)}] span={span_m:.2f} load={load_kNm:.1f} "
                  f"grade={grade} type={section_type}: NO FEASIBLE DESIGN FOUND -- skipped")
            continue

        rows.append(dict(
            span_m=span_m, load_kNm=load_kNm, grade=grade, section_type=section_type,
            h=best_result["h"], b=best_result["b"], tf=best_result["tf"], tw=best_result["tw"],
            util=best_result["util"], mass=best_result["mass"], cost=best_result["cost"],
            co2=best_result["co2"], governing="GA",  # replaces the original's DEFL/MOM tag;
            # GA optimises the full feasibility constraint (moment+shear+deflection combined
            # via HSSBeamEnv._ec3_analysis's governing-util logic), so a single governing-check
            # label is not directly meaningful the way it was for the original's per-check grid.
        ))

        if (i + 1) % 50 == 0 or i == len(contexts) - 1:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed
            eta = (len(contexts) - i - 1) / rate
            print(f"  [{i+1}/{len(contexts)}] elapsed={elapsed/60:.1f}min  ETA={eta/60:.1f}min")

    df = pd.DataFrame(rows)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    df.to_csv(args.out, index=False)
    print(f"\nDone. {len(df)}/{len(contexts)} contexts had a feasible design.")
    print(f"Ground truth written to {args.out}")
    print(f"Total wall time: {(time.time() - t0)/60:.1f} minutes")


if __name__ == "__main__":
    main()
